version: "3.8"

services: 
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./Jisho:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./Jisho:/var/www/html:delegated 
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports: 
      - '3306:3306'
    env_file: 
      - ./env/mysql.env
    networks:
      - app-network

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./Jisho:/var/www/html
    networks:
      - app-network

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./Jisho:/var/www/html
    entrypoint: ["php","/var/www/html/artisan"]
    networks:
      - app-network

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./Jisho:/var/www/html
    networks:
      - app-network

  kuromoji-service:
    image: node:14
    container_name: kuromoji_service
    working_dir: /app
    volumes:
      - ./kuromoji-service:/app
    command: bash -c "npm install && node index.js"
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
